name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x.x
    - name: Run scripts
      run: |
        yarn
        yarn lint
        yarn test --colors
      env:
        CI: true
